---
abstract: 'A library to access the iThenticate web service'
author:
  - 'Fred Moyer <fred@iparadigms.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-iThenticate
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SSLeay: 0.57
  RPC::XML: 1.36
  URI: 1.35
version: 0.15
